- name: webserver
  hosts: all
  become: true
  tasks:
  - name: installing
    yum:
     name: httpd
     state: latest
  - name: copy index file
    copy:
     src: "index.html"
     dest: /var/www/html
  - name: start_httpd
    systemd:
     name: httpd
     state: started