- name: block
  hosts: all
  become: true
  tasks:
  - blockinfile:
      path: /mnt/myblock.txt
      create: yes
      block:
         my data i am supercool /n
         me hi bhagwaan /n
         nilam bhi bhagwaan