#create role and mention it in our yaml file

#rolefile/tasks/main.yml
- name: update
  apt:
    upgrade: yes
    update_cache: yes
- name: install mysql
  apt:
    name: mysql-server
    state: latest
- name: service start and enable
  service:
    name: mysql
    state: started
    enabled: true

#add lines to file
- name: Insert/Update HTML surrounded by custom markers after <body> line
  blockinfile:
    path: /mnt/apache-tomcat-8.5.81/conf/context.xml
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "<Context>"
    block: |
      <Context>
      <Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource"
      maxTotal="100" maxIdle="30" maxWaitMillis="10000"
      username="admin" password="aishwarya19" driverClassName="com.mysql.jdbc.Driver"
      url="jdbc:mysql:// database-my.cwj1422nm29j.ap-northeast-1.rds.amazonaws.com:3306/studentapp"/>

#place jdbc connector [moba===> mv /home/ubuntu/mysql-connector.jar (tomcat_git_dir)]
- name: .jar file in remote
  copy:
    src: mysql-connector.jar
    dest: /mnt/apache-tomcat-8.5.81/lib/

#got an error of"The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
- name: install Python
  apt:
    name: python
    state: latest
- name: install pip
  apt:
    name: python3-pip
    state: latest
- name: install PyMySQL through pip (package installer for python)
  ansible_python_interpreter: /usr/bin/python3
  pip:
    name: pymysql
    state: latest

#create data base with help of mysql module
- name: update mysql root password for all root accounts  
  mysql_user:    
    login_user: admin  
    login_password: aishwarya19  
    check_implicit_admin: yes  
    priv: "*.*:ALL,GRANT"

- name: create a new database  
  mysql_db: name=studentapp state=present login_user=admin login_password=aishwarya19  
- name: add sample data to database  
  copy: src=data.sql dest=/tmp/data.sql  
- name: insert sample data into database  
  mysql_db: name=studentapp state=import target=/tmp/data.sql login_user=admin login_password=aishwarya19