#make [role-->ansible-galaxy init (role name)] in .yml file give role
- name: role playbook
  hosts: all
  become: true
  role:
    - tom_srv

#1 install java and unzip
- name: installation
  apt: 
    upgrade: yes
    update_cache: yes
- name:
  package:    
    name: "{{item}}"
    state: present
  loop:
    - openjdk-8-jdk
    - unzip
  
#2 get tomcat 8
- name: tomcat
  get_url: 
    url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
    dest: /mnt

#3 unzip
- name: unzip tomcat file
  command: tar -xvzf /mnt/apache-tomcat-8.5.81.tar.gz -C /mnt

#4 copy student.war file in webapps
- name: copy student.war to webapps
  copy: 
    src: /home/ubuntu/student.war
    dest: /mnt/apache-tomcat-8.5.81/webapps

#5 run
- name: run 
  command: nohup /mnt/apache-tomcat-8.5.81/bin/startup.sh &

