- name: for tomcat
  hosts: all
  become: true
  tasks:
  - name: downloading tomcat
    get_url:
      url: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz"
      dest: /usr/local
  - name: unzip tomcat
    unarchive:
      src: "/usr/local/apache-tomcat-8.5.81.tar.gz"
      dest: /usr/local
      remote_src: yes    
  - name: Run Tomcat
    shell: ./startup.sh
    args:
     chdir: /opt/apache-tomcat-9.0.1/bin