- name: demo
  hosts: all
  become: true   
  tasks:
  - name: forinstall
    w-get:           
      name: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz       
      state: latest 